# Generated by Django 6.0.8 on 2026-10-06 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Kod')),
                ('schedule', models.CharField(blank=True, help_text='Masalan: Du / Chor 18:00–20:00', max_length=200, verbose_name='Jadval')),
                ('room', models.CharField(blank=True, max_length=80, verbose_name='Xona')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paused', "To'xtatilgan"), ('archived', 'Arxiv')], db_index=True, default='active', max_length=16, verbose_name='Holat')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_minutes', models.PositiveIntegerField(default=90, verbose_name='Davomiyligi (daq.)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_on', models.DateField(db_index=True, verbose_name='Sana')),
                ('starts_at', models.TimeField(blank=True, null=True, verbose_name='Boshlanish')),
                ('status', models.CharField(choices=[('planned', 'Rejada'), ('completed', "O'tildi"), ('cancelled', 'Bekor')], db_index=True, default='planned', max_length=16, verbose_name='Holat')),
                ('homework', models.TextField(blank=True, verbose_name='Uyga vazifa')),
                ('notes', models.TextField(blank=True, verbose_name='Dars izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academy.group', verbose_name='Guruh')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='academy.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['-held_on', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='F.I.Sh.')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=80, verbose_name='Telegram')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paused', 'Tanaffus'), ('graduated', 'Bitirgan'), ('dropped', 'Ketgan')], db_index=True, default='active', max_length=16, verbose_name='Holat')),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate, verbose_name="Qo'shilgan")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academy.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Shogird',
                'verbose_name_plural': 'Shogirdlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kechikdi'), ('excused', 'Sababli')], default='present', max_length=16, verbose_name='Holat')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academy.lesson', verbose_name='Dars')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academy.student', verbose_name='Shogird')),
            ],
            options={
                'verbose_name': "Yo'qlama",
                'verbose_name_plural': "Yo'qlamalar",
            },
        ),
        migrations.CreateModel(
            name='SyllabusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('status', models.CharField(choices=[('planned', 'Rejada'), ('taught', "O'tildi"), ('skipped', "O'tkazib yuborildi")], db_index=True, default='planned', max_length=16, verbose_name='Holat')),
                ('taught_on', models.DateField(blank=True, null=True, verbose_name="O'tilgan sana")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='academy.group', verbose_name='Guruh')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_items', to='academy.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Guruh mavzusi',
                'verbose_name_plural': 'Guruh mavzulari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group', 'status'], name='academy_stu_group_i_9d359d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lesson', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='syllabusitem',
            unique_together={('group', 'topic')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'held_on'], name='academy_les_group_i_141e26_idx'),
        ),
    ]
