# Generated by Django 5.2.17 on 2026-10-06 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True, verbose_name="Bo'lim")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['module__order', 'module__title', 'order', 'title'], 'verbose_name': 'Mavzu', 'verbose_name_plural': 'Mavzular'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='syllabusitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='homework',
            field=models.TextField(blank=True, help_text="Shu mavzuda dars yaratilganda avtomatik qo'yiladi.", verbose_name='Uyga vazifa (shablon)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='resources',
            field=models.TextField(blank=True, help_text='Har qatorda bitta havola yoki manba.', verbose_name='Materiallar'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='uniq_attendance_lesson_student'),
        ),
        migrations.AddConstraint(
            model_name='syllabusitem',
            constraint=models.UniqueConstraint(fields=('group', 'topic'), name='uniq_syllabus_group_topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='academy.module', verbose_name="Bo'lim"),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('module', 'title'), name='uniq_topic_title_per_module'),
        ),
    ]
