# Generated by Django 5.2.17 on 2026-10-06 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_modules_topic_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Darsdagi faollik va uy vazifasi uchun baho. Bo'sh — baholanmagan.", null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Ball (0–100)'),
        ),
    ]
