# Generated by Django 5.2.17 on 2026-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_attendance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.CharField(blank=True, help_text='Hafta kunlari raqamlari (0 — dushanba), vergul bilan: 1,4,5', max_length=20, verbose_name='Dars kunlari'),
        ),
        migrations.AddField(
            model_name='group',
            name='ends_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AddField(
            model_name='group',
            name='starts_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.CharField(blank=True, help_text="Dars kunlari va vaqti tanlansa, avtomatik to'ldiriladi.", max_length=200, verbose_name='Jadval'),
        ),
    ]
