# Generated by Django 5.2.18 on 2026-10-07 06:51

import academy.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_group_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='academy.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=10, help_text='Shu vaqt tugaganda test avtomatik yakunlanadi.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Vaqt (daq.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='academy.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academy.quiz', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=academy.models.new_attempt_token, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ochilmagan'), ('active', 'Yechilmoqda'), ('finished', 'Tugatgan')], db_index=True, default='pending', max_length=16, verbose_name='Holat')),
                ('owner_key', models.CharField(blank=True, editable=False, max_length=64)),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Javoblar')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan')),
                ('timed_out', models.BooleanField(default=False, verbose_name='Vaqt tugadi')),
                ('correct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="To'g'ri javoblar")),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Savollar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='academy.lesson', verbose_name='Dars')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academy.quiz', verbose_name='Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='academy.student', verbose_name='Shogird')),
            ],
            options={
                'verbose_name': 'Test havolasi',
                'verbose_name_plural': 'Test havolalari',
                'ordering': ['student__full_name'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='uniq_quiz_attempt_lesson_student')],
            },
        ),
    ]
